services:
  api:
    build: .
    container_name: express-api
    ports:
      - "3000:3000"
    restart: always
    command: ["npm", "start"]
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - OWM_API_KEY=${OWM_API_KEY}
      - WEATHERAPI_API_KEY=${WEATHERAPI_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ALLOWLIST=${CORS_ALLOWLIST}
      - REDIS_URL=${REDIS_URL}
    networks:
      - express-api-network
    dns:
      - 8.8.8.8
      - 1.1.1.1

  db:
    image: postgres:15
    container_name: express-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - express-api-network

  redis:
    image: redis:8.8-m03-alpine3.23
    container_name: express-redis
    restart: always
    ports:
      - "6379"
    networks:
      - express-api-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db-data:

networks:
  express-api-network:
    driver: bridge
