/**
 * Sequelize/Umzug migration: create logs table with enum type and ip index
 */
import { Sequelize } from 'sequelize';

export async function up({context: queryInterface}) {
  await queryInterface.createTable('logs', {
    id: { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true },
    ip: { type: Sequelize.TEXT },
    route: { type: Sequelize.TEXT },
    method: { type: Sequelize.ENUM('GET','POST','PUT','DELETE','PATCH') },
    code : { type: Sequelize.INTEGER },
    description: { type: Sequelize.TEXT, allowNull: true },
    type: { type: Sequelize.ENUM('DEBUG','INFO','WARN','ERROR','FATAL') },
    created_at: { type: Sequelize.DATE, allowNull: false, defaultValue: Sequelize.fn('now') }
  });

  await queryInterface.addIndex('logs', ['ip'], { name: 'idx_logs_ip' });
}

export async function down({context: queryInterface}) {
  await queryInterface.removeIndex('logs', 'idx_logs_ip');
  await queryInterface.dropTable('logs');
  // drop enum type generated by Sequelize: enum_<table>_<column>
  await queryInterface.sequelize.query('DROP TYPE IF EXISTS "enum_logs_method"');
  await queryInterface.sequelize.query('DROP TYPE IF EXISTS "enum_logs_type"');
}
